# Generated by Django 4.2.4 on 2023-08-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_category_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategories',
        ),
    ]
