# Generated by Django 4.2.4 on 2023-08-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0004_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
