# Generated by Django 4.2.4 on 2023-08-12 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название категории')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='номер телефона')),
                ('additional_number', models.CharField(max_length=12, verbose_name='доп.номер')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('working_mode', models.CharField(max_length=25, verbose_name='режим работы')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='фотография')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя больници')),
                ('description', models.TextField(verbose_name='описание')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('category', models.ManyToManyField(related_name='hospitals', to='hospitals.category')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospitals.contact')),
            ],
            options={
                'verbose_name': 'Больница',
                'verbose_name_plural': 'Больници',
            },
        ),
    ]
